### ISSUE TITLE
Drawing characters are wrong

### ISSUE THREAD

**Issue by sur5r** [nnev/c128-kasse#8]
At some point, cc65 seems to have changed parts of the ASCII->PETSCII translation. This resulted in broken drawing characters on the main screen.

**Comment by stapelberg** [comment]
Was this actually an issue on the hardware as well, or only in the emulator? I don’t recall.

**Comment by sur5r** [comment]
Both. Will have to read the cc65 docs, I'm pretty sure this is documented.
